-- Run once in a Snowflake worksheet as ACCOUNTADMIN

USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS TLC_DB;
CREATE WAREHOUSE IF NOT EXISTS TLC_WH
    WITH WAREHOUSE_SIZE = 'X-SMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE;

GRANT ALL PRIVILEGES ON DATABASE TLC_DB  TO ROLE SYSADMIN;
GRANT ALL PRIVILEGES ON WAREHOUSE TLC_WH TO ROLE SYSADMIN;

USE ROLE SYSADMIN;
USE DATABASE TLC_DB;
USE WAREHOUSE TLC_WH;

CREATE SCHEMA IF NOT EXISTS TLC_DB.RAW;
CREATE SCHEMA IF NOT EXISTS TLC_DB.STAGING;
CREATE SCHEMA IF NOT EXISTS TLC_DB.MARTS;
CREATE SCHEMA IF NOT EXISTS TLC_DB.SNAPSHOTS;

USE ROLE ACCOUNTADMIN;
GRANT ALL PRIVILEGES ON SCHEMA TLC_DB.RAW       TO ROLE SYSADMIN;
GRANT ALL PRIVILEGES ON SCHEMA TLC_DB.STAGING   TO ROLE SYSADMIN;
GRANT ALL PRIVILEGES ON SCHEMA TLC_DB.MARTS     TO ROLE SYSADMIN;
GRANT ALL PRIVILEGES ON SCHEMA TLC_DB.SNAPSHOTS TO ROLE SYSADMIN;
GRANT CREATE VIEW  ON SCHEMA TLC_DB.STAGING TO ROLE SYSADMIN;
GRANT CREATE TABLE ON SCHEMA TLC_DB.MARTS   TO ROLE SYSADMIN;

USE ROLE SYSADMIN;

CREATE STAGE IF NOT EXISTS TLC_DB.RAW.TLC_STAGE FILE_FORMAT = (TYPE = 'PARQUET');

CREATE OR REPLACE TABLE TLC_DB.RAW.YELLOW_TRIPS_RAW (
    VENDORID              NUMBER,
    TPEP_PICKUP_DATETIME  TIMESTAMP_NTZ,
    TPEP_DROPOFF_DATETIME TIMESTAMP_NTZ,
    PASSENGER_COUNT       NUMBER,
    TRIP_DISTANCE         FLOAT,
    RATECODEID            NUMBER,
    STORE_AND_FWD_FLAG    VARCHAR(1),
    PULOCATIONID          NUMBER,
    DOLOCATIONID          NUMBER,
    PAYMENT_TYPE          NUMBER,
    FARE_AMOUNT           FLOAT,
    EXTRA                 FLOAT,
    MTA_TAX               FLOAT,
    TIP_AMOUNT            FLOAT,
    TOLLS_AMOUNT          FLOAT,
    IMPROVEMENT_SURCHARGE FLOAT,
    TOTAL_AMOUNT          FLOAT,
    CONGESTION_SURCHARGE  FLOAT,
    AIRPORT_FEE           FLOAT,
    CBD_CONGESTION_FEE    FLOAT,
    _LOADED_AT            TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE TLC_DB.RAW.TAXI_ZONE_LOOKUP (
    LOCATIONID   NUMBER,
    BOROUGH      VARCHAR,
    ZONE         VARCHAR,
    SERVICE_ZONE VARCHAR
);

SHOW TABLES IN SCHEMA TLC_DB.RAW;
SHOW GRANTS ON SCHEMA TLC_DB.STAGING;
